language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
linux: &linux
  os: linux
  dist: xenial
  addons:
    apt:
      packages:
        - libgdal1-dev
matrix:
  include:
    - <<: *linux

install:
  - pip install mesher
  - mesher.py