linux: &linux
  os: linux
  dist: bionic
  language: python
  env: CC=gcc-7 CXX=g++-7

osx: &osx
  os: osx
  language: generic

matrix:
  include:
    - <<: *linux
      python: "3.6"
    - <<: *linux
      python: "3.7"
    - <<: *osx
      osx_image: xcode11.3
      env: pyv="3.6.10"
    - <<: *osx
      osx_image: xcode11.3
      env: pyv="3.7.6"



before_install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh
  - git clone https://github.com/Chrismarsh/mesher.git
  - (cd mesher && git checkout $TRAVIS_BRANCH)
install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then eval "$(pyenv init -)"; pyenv activate mesher         ; fi
  - pip install --upgrade pip
  - pip install ./mesher/
script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then eval "$(pyenv init -)";pyenv activate mesher         ; fi
  - cd mesher/examples
  - bash ./runall.sh
deploy:
  provider: script
  script: bash .travis/deploy.sh
  on:
    tags: true