language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - 
addons:
  apt:
    packages:
      - libgdal1-dev
linux: &linux
  os: linux
  dist: xenial
matrix:
  include:
    - <<: *linux

install:
  - pip install mesher
  - mesher.py