language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
addons:
  apt:
    packages:
      - libgdal1-dev
linux: &linux
  os: linux
  dist: xenial
matrix:
  include:
    - <<: *linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
install:
  - pip install mesher
script:
  - wget https://github.com/Chrismarsh/mesher/raw/master/examples.zip
  - unzip -o examples
  - mesher.py examples/flat/flat.py